### ISSUE TITLE
Choose directory of Sketchpacks library

### ISSUE THREAD

**Issue by solo-s** [sketchpacks/feedback#29] opened 2017-06-09 16:29 UTC
I think it will be cool to sync library in any cloud service within separate machines.
All copies of sketchpack looks into file change time and sync installed plugins if file was updated from last time. Something like this.

**Comment by adamkirkwood** [comment] 2017-06-28 07:29
@e1ectron We are close to having `0.6.0` be available, which will support multi-machine syncing.

If you wish to get a release candidate build to try out before we release `0.6.0`, please email us at team@sketchpacks.com and we'll provide you a build.

**Comment by adamkirkwood** [comment] 2017-08-11 17:34
Duplicate of #8.

**Closed as completed by adamkirkwood** 2017-08-11 17:34 UTC
Labels: Status: In Progress
